### ISSUE TITLE
Contributions blocked

### ISSUE THREAD

**Issue by deonlewisduke** [microsoft/Quantum-NC#43]
Why can't you use a quantum computer running q# to apply the massive and multi-branch myriad changes that will result from 70 researchers constantly experimenting? Where are all the changes stored but in each separate locale? This is a problem.

**Comment by msoeken** [comment]
This seems out of scope.

**Comment by deonlewisduke** [comment]
This was a test to see who would show up. Who'd show off. I made 1 small edit to the source code of the quantum system, like I always do. Attempting a 1 is less than zero code to run clear in a well defined coast is clear function. If 0 is all than any other number variable is a part of the all and represents a deviation from #solidstate so no code should run. And you blocked me.from contributing.
