### ISSUE TITLE
How come the non-commercial restriction?

### ISSUE THREAD

**Issue by amirebrahimi** [microsoft/Quantum-NC#45]
I'm curious why this repository is called out specifically for only non-commercial use. Can someone please clarify?

**Comment by Gustavo-Loggin** [comment]
...

**Comment by WhiteBlackGoose** [comment]
Check [license](https://github.com/microsoft/Quantum-NC/blob/main/LICENSE)

**Comment by amirebrahimi** [comment]
Thanks, @WhiteBlackGoose. My question was mainly to ask what isn't in there, which is the motivation to restrict only to non-commercial, but it really isn't an issue since we'll all probably be in research-mode for some time ahead.
