### ISSUE TITLE
Going quantum

### ISSUE THREAD

**Issue by deonlewisduke** [microsoft/Quantum-NC#68]
https://github.com/MicrosoftDocs/quantum-docs-pr/blob/articles/TOC.yml/aecd5d3b3837758e7ff5c1949ff4ede3c5be54e4

**Comment by msoeken** [comment]
Link is 404

**Comment by deonlewisduke** [comment]
Link is not, you are not microsoft365

Get OPTION##                    for                      #SOLID<https://aka.ms/AAb9ysg>
________________________________
